services:
  order-db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=demo-payment
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=minjeong
      - MYSQL_PASSWORD=password
      - TZ=UTC
    command: # 명령어 실행
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --lower_case_table_names=1
    volumes:
      - ./mysql:/var/lib/mysql
  order-redis-db:
    image: redis:alpine3.20
    ports:
      - "6379:6379"
    command: redis-server /usr/local/conf/redis.conf
    volumes:
      - ./redis/data:/data
      - ./redis/conf/redis.conf:/usr/local/conf/redis.conf

